### ISSUE TITLE
namespace Firebase not found (new download)

### ISSUE THREAD

**Issue by SrirachaSource** [google/mechahamster#31]
I'm updating Firebase in Unity project (it's been at least 2 years) and having lots of trouble. I downloaded this example and it doesn't even build in Unity 2017.4 getting: `error CS0246: The type or namespace name 'Firebase' could not be found. Are you missing an assembly reference?`

I'm getting this same type of error in my project with the new firebase, it's like the Editor scripts are missing.

**Comment by AnandGameDev** [comment]
try Dotnet 3
